# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_graphique_zoo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(443, 339)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_animal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_animal.setGeometry(QtCore.QRect(150, 50, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.pushButton_animal.setFont(font)
        self.pushButton_animal.setObjectName("pushButton_animal")
        self.pushButton_enclos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enclos.setGeometry(QtCore.QRect(150, 120, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_enclos.setFont(font)
        self.pushButton_enclos.setObjectName("pushButton_enclos")
        self.pushButton_quitter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quitter.setGeometry(QtCore.QRect(150, 190, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_quitter.setFont(font)
        self.pushButton_quitter.setObjectName("pushButton_quitter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_animal.setText(_translate("MainWindow", "Animal"))
        self.pushButton_enclos.setText(_translate("MainWindow", "Enclos"))
        self.pushButton_quitter.setText(_translate("MainWindow", "Quitter"))
